# Generated by Django 3.1.12 on 2021-08-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0008_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
